Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/IndentationWidth:
  Width: 2
